
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: k8s-webhook-common-service
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: k8s-webhook-common
    app.kubernetes.io/part-of: k8s-webhook-common
    app.kubernetes.io/managed-by: kustomize
  name: k8s-webhook-common-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: my-project-name
